function build_stereo_ibvs_sim_stage1_clean(projectDir)
% 代码作用：
% 只生成Stage 1离线仿真模型stereo_ibvs_sim_stage1.slx。
% 本脚本只读取stereo_ibvs_core.slx和stereo_ibvs_config.m，
% 不修改、不保存这两个文件，也不生成其他辅助文件。
%
% 输入参数含义：
% projectDir：
% simulink_new工程目录。可以省略，脚本会自动查找。
%
% 输出参数含义：
% 本函数没有输出参数。
% 成功后只生成：
% simulink_new/sim/stereo_ibvs_sim_stage1.slx

if nargin < 1
    projectDir = '';
end

%% 1. 查找core和config
[projectDir, coreFile, configFile, simDir] = ...
    locateProjectFiles(projectDir);

coreDir = fileparts(coreFile);
configDir = fileparts(configFile);

addpath(coreDir);
addpath(configDir);

fprintf('\n核心模型：%s\n', coreFile);
fprintf('配置文件：%s\n', configFile);
fprintf('仿真输出：%s\n', simDir);

%% 2. 读取配置，不修改配置文件
run(configFile);

if evalin('base', 'exist(''cfg'',''var'')') ~= 1
    error('StereoIBVSSim:CfgMissing', ...
        '运行配置文件后，基础工作区中没有生成cfg。');
end

cfgLocal = evalin('base', 'cfg');

validateConfiguration(cfgLocal);

% 仅在当前离线仿真工作区中临时开放Stage 1。
% 不修改stereo_ibvs_config.m。
cfgLocal.stage1CalibrationReady = true;
assignin('base', 'cfg', cfgLocal);

%% 3. 加载正确的core模型
[~, coreModelName, ~] = fileparts(coreFile);

if bdIsLoaded(coreModelName)
    loadedCoreFile = get_param(coreModelName, 'FileName');

    if ~samePath(loadedCoreFile, coreFile)
        close_system(coreModelName, 0);
    end
end

load_system(coreFile);

loadedCoreFile = get_param(coreModelName, 'FileName');

if ~samePath(loadedCoreFile, coreFile)
    error('StereoIBVSSim:WrongCoreLoaded', ...
        ['当前加载的core不是目标文件。\n' ...
         '实际：%s\n目标：%s'], ...
        loadedCoreFile, coreFile);
end

% 只做编译检查，不修改、不保存core模型。
set_param(coreModelName, 'SimulationCommand', 'update');

% core自己的InitFcn可能重新运行配置，因此更新后再次设置离线许可。
cfgLocal = evalin('base', 'cfg');
cfgLocal.stage1CalibrationReady = true;
assignin('base', 'cfg', cfgLocal);

%% 4. 新建sim模型
simModelName = 'stereo_ibvs_sim_stage1';
simModelFile = fullfile(simDir, [simModelName '.slx']);

if bdIsLoaded(simModelName)
    close_system(simModelName, 0);
end

if isfile(simModelFile)
    delete(simModelFile);
end

new_system(simModelName);
open_system(simModelName);

try
    configureSimulationModel(simModelName);
    configureSimulationCallbacks( ...
        simModelName, configFile, coreDir, configDir);

    addDescription(simModelName);

    scenarioPath = addStage1Scenario(simModelName);

    coreBlockPath = addCoreReference( ...
        simModelName, coreModelName);

    addOutputBlocks(simModelName);

    connectTopLevel( ...
        simModelName, scenarioPath, coreBlockPath);

    % 编译检查新生成的sim模型。
    set_param(simModelName, ...
        'SimulationCommand', 'update');

    save_system(simModelName, simModelFile);

    open_system(simModelName);
    set_param(simModelName, ...
        'ZoomFactor', 'FitSystem');

catch ME
    try
        save_system(simModelName, simModelFile);
    catch
    end

    fprintf(2, '\n生成sim模型失败：\n%s\n', ...
        getReport(ME, 'extended', ...
        'hyperlinks', 'off'));

    rethrow(ME);
end

fprintf('\n生成成功：\n%s\n', simModelFile);
fprintf('\n运行方式：\n');
fprintf('sim(''%s'');\n', simModelName);
fprintf('\n测试流程：\n');
fprintf('0~0.5秒：控制器关闭，关节速度为0。\n');
fprintf('0.5~3秒：目标偏离中心，产生非零关节速度。\n');
fprintf('3~4.5秒：目标回到中心，关节速度回到0附近。\n');
fprintf('4.5~6秒：视觉无效，关节速度持续为0。\n');

end


function configureSimulationModel(modelName)
% 代码作用：
% 设置离线仿真时间和离散求解器。
%
% 输入参数含义：
% modelName：
% 仿真模型名称。
%
% 输出参数含义：
% 本函数没有输出参数。

set_param( ...
    modelName, ...
    'StartTime', '0', ...
    'StopTime', '6', ...
    'SolverType', 'Fixed-step', ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', 'cfg.Ts', ...
    'ReturnWorkspaceOutputs', 'on', ...
    'SignalLogging', 'on', ...
    'SignalLoggingName', 'logsout');
end


function configureSimulationCallbacks( ...
    modelName, configFile, coreDir, configDir)
% 代码作用：
% 只在生成的sim模型内部设置初始化和停止回调。
% 不修改core或config文件。
%
% 输入参数含义：
% modelName：
% 仿真模型名称。
%
% configFile：
% 配置文件完整路径。
%
% coreDir：
% core模型目录。
%
% configDir：
% 配置文件目录。
%
% 输出参数含义：
% 本函数没有输出参数。

configEscaped = escapeQuotes(configFile);
coreDirEscaped = escapeQuotes(coreDir);
configDirEscaped = escapeQuotes(configDir);

initCallback = sprintf([ ...
    'addpath(''%s'');' ...
    'addpath(''%s'');' ...
    'run(''%s'');' ...
    'cfg.stage1CalibrationReady=true;' ...
    'assignin(''base'',''cfg'',cfg);'], ...
    coreDirEscaped, ...
    configDirEscaped, ...
    configEscaped);

stopCallback = [ ...
    'if evalin(''base'',' ...
    '''exist(''''cfg'''',''''var'''')==1''),' ...
    'cfg=evalin(''base'',''cfg'');' ...
    'cfg.stage1CalibrationReady=false;' ...
    'assignin(''base'',''cfg'',cfg);' ...
    'end'];

set_param(modelName, 'InitFcn', initCallback);
set_param(modelName, 'StopFcn', stopCallback);
set_param(modelName, 'CloseFcn', stopCallback);
end


function addDescription(modelName)
% 代码作用：
% 在生成的sim模型顶部添加测试说明。
%
% 输入参数含义：
% modelName：
% 仿真模型名称。
%
% 输出参数含义：
% 本函数没有输出参数。

description = sprintf([ ...
    'Stage 1离线仿真\n' ...
    '0~0.5 s：控制器关闭\n' ...
    '0.5~3.0 s：目标偏离中心\n' ...
    '3.0~4.5 s：目标回到中心\n' ...
    '4.5~6.0 s：视觉无效，速度持续为0\n' ...
    '该模型不连接ROS 2和真实机械臂']);

annotation = Simulink.Annotation( ...
    modelName, description);

annotation.Position = [35 20 540 110];
end


function scenarioPath = addStage1Scenario(modelName)
% 代码作用：
% 创建Stage 1固定关节位置、视觉特征、使能和复位测试输入。
%
% 输出参数含义：
% scenarioPath：
% 测试场景子系统完整路径。

scenarioPath = [ ...
    modelName '/Stage1 Test Scenario'];

add_block( ...
    'simulink/Ports & Subsystems/Subsystem', ...
    scenarioPath, ...
    'Position', [45 155 310 505]);

Simulink.SubSystem.deleteContents(scenarioPath);

%% qRaw：固定合法关节位置
addVectorConstant( ...
    scenarioPath, ...
    'Initial Joint Position', ...
    'cfg.qInitial', ...
    [30 30 220 65]);

addOutport( ...
    scenarioPath, 'qRaw', ...
    1, '[7 1]', ...
    [700 35 730 55]);

%% visionFeatureRaw：分三阶段切换
offsetFeature = [ ...
    '[1;1;' ...
    'cfg.cameraIntrinsicsStage1(3)+200;' ...
    'cfg.cameraIntrinsicsStage1(4)+120;' ...
    'cfg.cameraIntrinsicsStage1(7)+120;' ...
    'cfg.cameraIntrinsicsStage1(8)+120;' ...
    '120;120]'];

centeredFeature = [ ...
    '[1;1;' ...
    'cfg.cameraIntrinsicsStage1(3);' ...
    'cfg.cameraIntrinsicsStage1(4);' ...
    'cfg.cameraIntrinsicsStage1(7)-80;' ...
    'cfg.cameraIntrinsicsStage1(8);' ...
    '120;120]'];

addVectorConstant( ...
    scenarioPath, ...
    'Offset Vision Feature', ...
    offsetFeature, ...
    [30 110 235 145]);

addVectorConstant( ...
    scenarioPath, ...
    'Centered Vision Feature', ...
    centeredFeature, ...
    [30 170 235 205]);

addVectorConstant( ...
    scenarioPath, ...
    'Invalid Vision Feature', ...
    'zeros(8,1)', ...
    [30 230 235 265]);

addStepBlock( ...
    scenarioPath, ...
    'Center Target at 3s', ...
    '3', '0', '1', ...
    [275 140 415 175]);

addStepBlock( ...
    scenarioPath, ...
    'Invalidate Vision at 4p5s', ...
    '4.5', '0', '1', ...
    [275 230 435 265]);

addSwitchBlock( ...
    scenarioPath, ...
    'Select Centered Feature', ...
    [460 120 545 210]);

addSwitchBlock( ...
    scenarioPath, ...
    'Select Invalid Feature', ...
    [585 160 670 250]);

add_line( ...
    scenarioPath, ...
    'Centered Vision Feature/1', ...
    'Select Centered Feature/1', ...
    'autorouting', 'on');

add_line( ...
    scenarioPath, ...
    'Center Target at 3s/1', ...
    'Select Centered Feature/2', ...
    'autorouting', 'on');

add_line( ...
    scenarioPath, ...
    'Offset Vision Feature/1', ...
    'Select Centered Feature/3', ...
    'autorouting', 'on');

add_line( ...
    scenarioPath, ...
    'Invalid Vision Feature/1', ...
    'Select Invalid Feature/1', ...
    'autorouting', 'on');

add_line( ...
    scenarioPath, ...
    'Invalidate Vision at 4p5s/1', ...
    'Select Invalid Feature/2', ...
    'autorouting', 'on');

add_line( ...
    scenarioPath, ...
    'Select Centered Feature/1', ...
    'Select Invalid Feature/3', ...
    'autorouting', 'on');

addOutport( ...
    scenarioPath, ...
    'visionFeatureRaw', ...
    2, '[8 1]', ...
    [700 195 730 215]);

%% zoomPositionStepsRaw：Stage 1固定为初始步数
addVectorConstant( ...
    scenarioPath, ...
    'Initial Zoom Position', ...
    'cfg.zoomInitialSteps', ...
    [30 315 220 350]);

addOutport( ...
    scenarioPath, ...
    'zoomPositionStepsRaw', ...
    3, '[2 1]', ...
    [700 310 730 330]);

%% controllerEnableRaw：0.5秒后使能
addStepBlock( ...
    scenarioPath, ...
    'Controller Enable', ...
    '0.5', '0', '1', ...
    [285 380 435 415]);

addOutport( ...
    scenarioPath, ...
    'controllerEnableRaw', ...
    4, '1', ...
    [700 385 730 405]);

%% resetRaw：固定为0
addScalarConstant( ...
    scenarioPath, ...
    'Reset', '0', ...
    [285 450 435 485]);

addOutport( ...
    scenarioPath, ...
    'resetRaw', ...
    5, '1', ...
    [700 455 730 475]);

%% 场景子系统内部连线
add_line( ...
    scenarioPath, ...
    'Initial Joint Position/1', ...
    'qRaw/1', ...
    'autorouting', 'on');

add_line( ...
    scenarioPath, ...
    'Select Invalid Feature/1', ...
    'visionFeatureRaw/1', ...
    'autorouting', 'on');

add_line( ...
    scenarioPath, ...
    'Initial Zoom Position/1', ...
    'zoomPositionStepsRaw/1', ...
    'autorouting', 'on');

add_line( ...
    scenarioPath, ...
    'Controller Enable/1', ...
    'controllerEnableRaw/1', ...
    'autorouting', 'on');

add_line( ...
    scenarioPath, ...
    'Reset/1', ...
    'resetRaw/1', ...
    'autorouting', 'on');
end


function coreBlockPath = addCoreReference( ...
    modelName, coreModelName)
% 代码作用：
% 创建引用stereo_ibvs_core的Model块。
%
% 输入参数含义：
% modelName：
% 仿真模型名称。
%
% coreModelName：
% core模型名称。
%
% 输出参数含义：
% coreBlockPath：
% Model块完整路径。

coreBlockPath = [ ...
    modelName '/Stereo IBVS Core'];

add_block( ...
    'simulink/Ports & Subsystems/Model', ...
    coreBlockPath, ...
    'Position', [455 165 735 465]);

set_param( ...
    coreBlockPath, ...
    'ModelName', coreModelName, ...
    'SimulationMode', 'Normal');

try
    Simulink.BlockDiagram.refreshBlocks(modelName);
catch
    set_param(modelName, ...
        'SimulationCommand', 'update');
end

portHandles = get_param( ...
    coreBlockPath, 'PortHandles');

if numel(portHandles.Inport) ~= 5 || ...
        numel(portHandles.Outport) ~= 3
    error('StereoIBVSSim:CorePortMismatch', ...
        ['core接口不正确。\n' ...
         '实际输入%d个、输出%d个；' ...
         '要求输入5个、输出3个。'], ...
        numel(portHandles.Inport), ...
        numel(portHandles.Outport));
end
end


function addOutputBlocks(modelName)
% 代码作用：
% 创建顶层输出、Scope和To Workspace模块。
%
% 输入参数含义：
% modelName：
% 仿真模型名称。
%
% 输出参数含义：
% 本函数没有输出参数。

addOutport( ...
    modelName, ...
    'jointVelocityCmd', ...
    1, '[7 1]', ...
    [1115 180 1145 200]);

addOutport( ...
    modelName, ...
    'zoomStepRateCmd', ...
    2, '[2 1]', ...
    [1115 290 1145 310]);

addOutport( ...
    modelName, ...
    'controllerStatus', ...
    3, '[12 1]', ...
    [1115 400 1145 420]);

add_block( ...
    'simulink/Sinks/Scope', ...
    [modelName '/Joint Velocity Scope'], ...
    'Position', [880 110 1010 195]);

add_block( ...
    'simulink/Sinks/Scope', ...
    [modelName '/Controller Status Scope'], ...
    'Position', [880 435 1010 520]);

addToWorkspace( ...
    modelName, ...
    'Log Joint Velocity', ...
    'simJointVelocityCmd', ...
    [865 220 1035 250]);

addToWorkspace( ...
    modelName, ...
    'Log Zoom Step Rate', ...
    'simZoomStepRateCmd', ...
    [865 330 1035 360]);

addToWorkspace( ...
    modelName, ...
    'Log Controller Status', ...
    'simControllerStatus', ...
    [865 545 1035 575]);
end


function connectTopLevel( ...
    modelName, scenarioPath, coreBlockPath)
% 代码作用：
% 连接测试场景、core、顶层输出、Scope和数据记录模块。
%
% 输入参数含义：
% modelName：
% 仿真模型名称。
%
% scenarioPath：
% 测试场景子系统路径。
%
% coreBlockPath：
% core引用块路径。
%
% 输出参数含义：
% 本函数没有输出参数。

scenarioHandles = get_param( ...
    scenarioPath, 'PortHandles');

coreHandles = get_param( ...
    coreBlockPath, 'PortHandles');

% 测试场景五个输出连接到core五个输入。
for portIndex = 1:5
    add_line( ...
        modelName, ...
        scenarioHandles.Outport(portIndex), ...
        coreHandles.Inport(portIndex), ...
        'autorouting', 'on');
end

% core输出1：jointVelocityCmd
connectBlockPorts( ...
    modelName, ...
    coreBlockPath, 1, ...
    [modelName '/jointVelocityCmd'], 1);

connectBlockPorts( ...
    modelName, ...
    coreBlockPath, 1, ...
    [modelName '/Joint Velocity Scope'], 1);

connectBlockPorts( ...
    modelName, ...
    coreBlockPath, 1, ...
    [modelName '/Log Joint Velocity'], 1);

% core输出2：zoomStepRateCmd
connectBlockPorts( ...
    modelName, ...
    coreBlockPath, 2, ...
    [modelName '/zoomStepRateCmd'], 1);

connectBlockPorts( ...
    modelName, ...
    coreBlockPath, 2, ...
    [modelName '/Log Zoom Step Rate'], 1);

% core输出3：controllerStatus
connectBlockPorts( ...
    modelName, ...
    coreBlockPath, 3, ...
    [modelName '/controllerStatus'], 1);

connectBlockPorts( ...
    modelName, ...
    coreBlockPath, 3, ...
    [modelName '/Controller Status Scope'], 1);

connectBlockPorts( ...
    modelName, ...
    coreBlockPath, 3, ...
    [modelName '/Log Controller Status'], 1);
end


function connectBlockPorts( ...
    rootModel, sourcePath, sourcePort, ...
    destinationPath, destinationPort)
% 代码作用：
% 使用完整模块路径和端口句柄建立连线。
%
% 输入参数含义：
% rootModel：
% 顶层模型名称。
%
% sourcePath：
% 源模块完整路径。
%
% sourcePort：
% 源模块输出端口号。
%
% destinationPath：
% 目标模块完整路径。
%
% destinationPort：
% 目标模块输入端口号。
%
% 输出参数含义：
% 本函数没有输出参数。

sourceHandles = get_param( ...
    sourcePath, 'PortHandles');

destinationHandles = get_param( ...
    destinationPath, 'PortHandles');

add_line( ...
    rootModel, ...
    sourceHandles.Outport(sourcePort), ...
    destinationHandles.Inport(destinationPort), ...
    'autorouting', 'on');
end


function validateConfiguration(cfgLocal)
% 代码作用：
% 检查Stage 1仿真需要的配置参数和机器人模型。
%
% 输入参数含义：
% cfgLocal：
% stereo_ibvs_config生成的配置结构体。
%
% 输出参数含义：
% 本函数没有输出参数。

requiredFields = {
    'robot'
    'Ts'
    'qInitial'
    'zoomInitialSteps'
    'cameraIntrinsicsStage1'
    'cameraBodyName'
};

for fieldIndex = 1:numel(requiredFields)
    if ~isfield(cfgLocal, ...
            requiredFields{fieldIndex})
        error('StereoIBVSSim:MissingCfgField', ...
            'cfg缺少字段：%s', ...
            requiredFields{fieldIndex});
    end
end

if numel(homeConfiguration( ...
        cfgLocal.robot)) ~= 7
    error('StereoIBVSSim:RobotDOF', ...
        'cfg.robot必须是7自由度。');
end

if ~any(strcmp( ...
        cfgLocal.robot.BodyNames, ...
        cfgLocal.cameraBodyName))
    error('StereoIBVSSim:CameraBodyMissing', ...
        'cfg.robot中不存在相机刚体%s。', ...
        cfgLocal.cameraBodyName);
end

Jtest = geometricJacobian( ...
    cfgLocal.robot, ...
    reshape(cfgLocal.qInitial, 7, 1), ...
    cfgLocal.cameraBodyName);

if ~isequal(size(Jtest), [6 7])
    error('StereoIBVSSim:JacobianSize', ...
        '测试雅可比尺寸不是6×7。');
end
end


function addOutport( ...
    parentPath, blockName, portNumber, ...
    dimensions, position)
% 代码作用：
% 创建指定尺寸的Outport模块。

add_block( ...
    'simulink/Ports & Subsystems/Out1', ...
    [parentPath '/' blockName], ...
    'Position', position, ...
    'Port', num2str(portNumber), ...
    'PortDimensions', dimensions);
end


function addVectorConstant( ...
    parentPath, blockName, value, position)
% 代码作用：
% 创建保持Nx1列向量形状的Constant模块。

add_block( ...
    'simulink/Sources/Constant', ...
    [parentPath '/' blockName], ...
    'Position', position, ...
    'Value', value, ...
    'SampleTime', 'cfg.Ts', ...
    'VectorParams1D', 'off', ...
    'OutDataTypeStr', 'double');
end


function addScalarConstant( ...
    parentPath, blockName, value, position)
% 代码作用：
% 创建double标量Constant模块。

add_block( ...
    'simulink/Sources/Constant', ...
    [parentPath '/' blockName], ...
    'Position', position, ...
    'Value', value, ...
    'SampleTime', 'cfg.Ts', ...
    'OutDataTypeStr', 'double');
end


function addStepBlock( ...
    parentPath, blockName, stepTime, ...
    beforeValue, afterValue, position)
% 代码作用：
% 创建离散Step模块。

add_block( ...
    'simulink/Sources/Step', ...
    [parentPath '/' blockName], ...
    'Position', position, ...
    'Time', stepTime, ...
    'Before', beforeValue, ...
    'After', afterValue, ...
    'SampleTime', 'cfg.Ts', ...
    'OutDataTypeStr', 'double');
end


function addSwitchBlock( ...
    parentPath, blockName, position)
% 代码作用：
% 创建以中间输入为控制条件的Switch模块。

add_block( ...
    'simulink/Signal Routing/Switch', ...
    [parentPath '/' blockName], ...
    'Position', position, ...
    'Criteria', 'u2 >= Threshold', ...
    'Threshold', '0.5');
end


function addToWorkspace( ...
    modelName, blockName, ...
    variableName, position)
% 代码作用：
% 创建To Workspace数据记录模块。

add_block( ...
    'simulink/Sinks/To Workspace', ...
    [modelName '/' blockName], ...
    'Position', position, ...
    'VariableName', variableName, ...
    'SaveFormat', 'Timeseries', ...
    'MaxDataPoints', 'inf', ...
    'Decimation', '1');
end


function escaped = escapeQuotes(textValue)
% 代码作用：
% 转义模型回调字符串中的单引号。

escaped = strrep( ...
    textValue, '''', '''''');
end


function result = samePath(pathA, pathB)
% 代码作用：
% 判断两个路径是否指向同一个文件。

canonicalA = char( ...
    java.io.File(pathA).getCanonicalPath());

canonicalB = char( ...
    java.io.File(pathB).getCanonicalPath());

result = strcmp(canonicalA, canonicalB);
end


function [projectDir, coreFile, ...
    configFile, simDir] = locateProjectFiles(projectDir)
% 代码作用：
% 自动查找core模型和配置文件。
%
% 输出参数含义：
% projectDir：
% 工程根目录。
%
% coreFile：
% stereo_ibvs_core.slx完整路径。
%
% configFile：
% stereo_ibvs_config.m完整路径。
%
% simDir：
% sim模型输出目录。

scriptDir = fileparts(mfilename('fullpath'));

candidateRoots = {};

if ~isempty(projectDir)
    candidateRoots{end+1} = char(projectDir);
end

candidateRoots = [candidateRoots, {
    scriptDir
    fileparts(scriptDir)
    pwd
    fileparts(pwd)
}];

projectDir = '';
coreFile = '';
configFile = '';

for rootIndex = 1:numel(candidateRoots)
    root = candidateRoots{rootIndex};

    if isempty(root) || ~isfolder(root)
        continue;
    end

    structuredCore = fullfile( ...
        root, 'core', ...
        'stereo_ibvs_core.slx');

    structuredConfig = fullfile( ...
        root, 'config', ...
        'stereo_ibvs_config.m');

    flatCore = fullfile( ...
        root, 'stereo_ibvs_core.slx');

    flatConfig = fullfile( ...
        root, 'stereo_ibvs_config.m');

    if isfile(structuredCore) && ...
            isfile(structuredConfig)
        projectDir = root;
        coreFile = structuredCore;
        configFile = structuredConfig;
        break;
    end

    if isfile(flatCore) && ...
            isfile(flatConfig)
        projectDir = root;
        coreFile = flatCore;
        configFile = flatConfig;
        break;
    end
end

if isempty(projectDir)
    error('StereoIBVSSim:ProjectNotFound', ...
        ['没有找到stereo_ibvs_core.slx和' ...
         'stereo_ibvs_config.m。']);
end

simDir = fullfile(projectDir, 'sim');

if ~isfolder(simDir)
    mkdir(simDir);
end
end
