function build_stereo_ibvs_sim_stage1_v2(projectDir)
% 代码作用：
% 自动生成Stage 1离线仿真模型stereo_ibvs_sim_stage1.slx。
% 该模型通过Model块引用现有stereo_ibvs_core.slx。
%
% 输入参数含义：
% projectDir：
% simulink_new目录。可以省略，脚本会自动查找。
%
% 输出参数含义：
% 本函数没有输出参数。
% 成功后会在sim目录生成stereo_ibvs_sim_stage1.slx。

if nargin < 1
    projectDir = '';
end

%% 1. 查找文件
[projectDir,coreFile,configFile,simDir] = ...
    locateProjectFiles(projectDir);

coreDir = fileparts(coreFile);
configDir = fileparts(configFile);

addpath(coreDir);
addpath(configDir);
addpath(simDir);

fprintf('\n核心模型：%s\n',coreFile);
fprintf('配置文件：%s\n',configFile);
fprintf('仿真目录：%s\n',simDir);

%% 2. 为配置文件加入离线仿真许可
ensureSimulationOverride(configFile);

assignin('base','STEREO_IBVS_SIMULATION_MODE',true);
run(configFile);

cfgLocal = evalin('base','cfg');
validateConfiguration(cfgLocal);

%% 3. 加载并检查正确的core模型
[~,coreModelName,~] = fileparts(coreFile);

if bdIsLoaded(coreModelName)
    loadedFile = get_param(coreModelName,'FileName');

    if ~samePath(loadedFile,coreFile)
        close_system(coreModelName,0);
    end
end

load_system(coreFile);

if ~samePath(get_param(coreModelName,'FileName'),coreFile)
    error('StereoIBVSSim:WrongCore', ...
        'MATLAB加载的不是指定的stereo_ibvs_core.slx。');
end

repairKinematicsBlocks(coreModelName,cfgLocal);
save_system(coreModelName);

set_param(coreModelName,'SimulationCommand','update');

%% 4. 创建仿真模型
simModelName = 'stereo_ibvs_sim_stage1';
simModelFile = fullfile(simDir,[simModelName '.slx']);

if bdIsLoaded(simModelName)
    close_system(simModelName,0);
end

if isfile(simModelFile)
    backupFile = fullfile(simDir, ...
        [simModelName '_backup_' ...
        char(datetime('now','Format','yyyyMMdd_HHmmss')) ...
        '.slx']);

    copyfile(simModelFile,backupFile);
    fprintf('旧模型已备份：%s\n',backupFile);
end

new_system(simModelName);
open_system(simModelName);

try
    set_param( ...
        simModelName, ...
        'StartTime','0', ...
        'StopTime','6', ...
        'SolverType','Fixed-step', ...
        'Solver','FixedStepDiscrete', ...
        'FixedStep','cfg.Ts', ...
        'ReturnWorkspaceOutputs','on');

    configureCallbacks(simModelName,configFile,coreDir,configDir);

    scenarioPath = buildScenario(simModelName);

    coreBlockPath = [simModelName '/Stereo IBVS Core'];

    add_block( ...
        'simulink/Ports & Subsystems/Model', ...
        coreBlockPath, ...
        'Position',[430 155 700 455]);

    set_param( ...
        coreBlockPath, ...
        'ModelName',coreModelName, ...
        'SimulationMode','Normal');

    try
        Simulink.BlockDiagram.refreshBlocks(simModelName);
    catch
        set_param(simModelName,'SimulationCommand','update');
    end

    coreHandles = get_param(coreBlockPath,'PortHandles');

    if numel(coreHandles.Inport) ~= 5 || ...
            numel(coreHandles.Outport) ~= 3
        error('StereoIBVSSim:CorePorts', ...
            ['core接口错误：实际输入%d个、输出%d个，' ...
             '应为输入5个、输出3个。'], ...
            numel(coreHandles.Inport), ...
            numel(coreHandles.Outport));
    end

    addOutputsAndLogging(simModelName);
    connectTopLevel(simModelName,scenarioPath,coreBlockPath);

    set_param(simModelName,'SimulationCommand','update');
    save_system(simModelName,simModelFile);

    open_system(simModelName);
    set_param(simModelName,'ZoomFactor','FitSystem');

catch ME
    try
        save_system(simModelName,simModelFile);
    catch
    end

    assignin('base','STEREO_IBVS_SIMULATION_MODE',false);

    fprintf(2,'\n构建失败：\n%s\n', ...
        getReport(ME,'extended','hyperlinks','off'));

    rethrow(ME);
end

fprintf('\n生成成功：%s\n',simModelFile);
fprintf('\n测试过程：\n');
fprintf('0~0.5秒：控制器关闭，速度为0。\n');
fprintf('0.5~3秒：目标偏离中心，产生非零速度。\n');
fprintf('3~4.5秒：目标回到中心，速度回到0附近。\n');
fprintf('4.5~6秒：视觉无效，持续输出0速度。\n');
fprintf('\n运行：sim(''%s'')\n',simModelName);

end


function scenarioPath = buildScenario(modelName)
% 代码作用：
% 创建Stage 1离线测试输入。
%
% 输出参数含义：
% scenarioPath：
% 测试场景子系统完整路径。

scenarioPath = [modelName '/Stage1 Test Scenario'];

add_block( ...
    'simulink/Ports & Subsystems/Subsystem', ...
    scenarioPath, ...
    'Position',[40 145 295 500]);

Simulink.SubSystem.deleteContents(scenarioPath);

%% qRaw
addVectorConstant( ...
    scenarioPath,'Initial Joint Position', ...
    'cfg.qInitial',[30 30 205 60]);

addOutport( ...
    scenarioPath,'qRaw',1,'[7 1]', ...
    [675 35 705 55]);

%% visionFeatureRaw
offsetFeature = [ ...
    '[1;1;' ...
    'cfg.cameraIntrinsicsStage1(3)+200;' ...
    'cfg.cameraIntrinsicsStage1(4)+120;' ...
    'cfg.cameraIntrinsicsStage1(7)+120;' ...
    'cfg.cameraIntrinsicsStage1(8)+120;' ...
    '120;120]'];

centerFeature = [ ...
    '[1;1;' ...
    'cfg.cameraIntrinsicsStage1(3);' ...
    'cfg.cameraIntrinsicsStage1(4);' ...
    'cfg.cameraIntrinsicsStage1(7)-80;' ...
    'cfg.cameraIntrinsicsStage1(8);' ...
    '120;120]'];

addVectorConstant( ...
    scenarioPath,'Offset Vision Feature', ...
    offsetFeature,[30 105 225 135]);

addVectorConstant( ...
    scenarioPath,'Centered Vision Feature', ...
    centerFeature,[30 165 225 195]);

addVectorConstant( ...
    scenarioPath,'Invalid Vision Feature', ...
    'zeros(8,1)',[30 225 225 255]);

addStep( ...
    scenarioPath,'Center at 3s', ...
    '3','0','1',[265 135 390 165]);

addStep( ...
    scenarioPath,'Invalidate at 4p5s', ...
    '4.5','0','1',[265 225 405 255]);

addSwitch( ...
    scenarioPath,'Select Centered', ...
    [430 120 510 200]);

addSwitch( ...
    scenarioPath,'Select Invalid', ...
    [550 155 630 245]);

add_line( ...
    scenarioPath, ...
    'Centered Vision Feature/1', ...
    'Select Centered/1', ...
    'autorouting','on');

add_line( ...
    scenarioPath, ...
    'Center at 3s/1', ...
    'Select Centered/2', ...
    'autorouting','on');

add_line( ...
    scenarioPath, ...
    'Offset Vision Feature/1', ...
    'Select Centered/3', ...
    'autorouting','on');

add_line( ...
    scenarioPath, ...
    'Invalid Vision Feature/1', ...
    'Select Invalid/1', ...
    'autorouting','on');

add_line( ...
    scenarioPath, ...
    'Invalidate at 4p5s/1', ...
    'Select Invalid/2', ...
    'autorouting','on');

add_line( ...
    scenarioPath, ...
    'Select Centered/1', ...
    'Select Invalid/3', ...
    'autorouting','on');

addOutport( ...
    scenarioPath,'visionFeatureRaw',2,'[8 1]', ...
    [675 190 705 210]);

%% zoomPositionStepsRaw
addVectorConstant( ...
    scenarioPath,'Initial Zoom Position', ...
    'cfg.zoomInitialSteps',[30 300 205 330]);

addOutport( ...
    scenarioPath,'zoomPositionStepsRaw',3,'[2 1]', ...
    [675 295 705 315]);

%% controllerEnableRaw
addStep( ...
    scenarioPath,'Controller Enable', ...
    '0.5','0','1',[265 365 410 395]);

addOutport( ...
    scenarioPath,'controllerEnableRaw',4,'1', ...
    [675 370 705 390]);

%% resetRaw
addScalarConstant( ...
    scenarioPath,'Reset','0', ...
    [265 430 410 460]);

addOutport( ...
    scenarioPath,'resetRaw',5,'1', ...
    [675 435 705 455]);

%% 连线
add_line( ...
    scenarioPath, ...
    'Initial Joint Position/1','qRaw/1', ...
    'autorouting','on');

add_line( ...
    scenarioPath, ...
    'Select Invalid/1','visionFeatureRaw/1', ...
    'autorouting','on');

add_line( ...
    scenarioPath, ...
    'Initial Zoom Position/1', ...
    'zoomPositionStepsRaw/1', ...
    'autorouting','on');

add_line( ...
    scenarioPath, ...
    'Controller Enable/1', ...
    'controllerEnableRaw/1', ...
    'autorouting','on');

add_line( ...
    scenarioPath, ...
    'Reset/1','resetRaw/1', ...
    'autorouting','on');
end


function addOutputsAndLogging(modelName)
% 代码作用：
% 创建顶层输出、Scope和To Workspace记录模块。

addOutport( ...
    modelName,'jointVelocityCmd',1,'[7 1]', ...
    [1090 175 1120 195]);

addOutport( ...
    modelName,'zoomStepRateCmd',2,'[2 1]', ...
    [1090 285 1120 305]);

addOutport( ...
    modelName,'controllerStatus',3,'[12 1]', ...
    [1090 395 1120 415]);

add_block( ...
    'simulink/Sinks/Scope', ...
    [modelName '/Joint Velocity Scope'], ...
    'Position',[855 110 980 190]);

add_block( ...
    'simulink/Sinks/Scope', ...
    [modelName '/Controller Status Scope'], ...
    'Position',[855 430 980 510]);

addToWorkspace( ...
    modelName,'Log Joint Velocity', ...
    'simJointVelocityCmd',[840 215 1010 245]);

addToWorkspace( ...
    modelName,'Log Zoom Step Rate', ...
    'simZoomStepRateCmd',[840 325 1010 355]);

addToWorkspace( ...
    modelName,'Log Controller Status', ...
    'simControllerStatus',[840 535 1010 565]);
end


function connectTopLevel( ...
    modelName,scenarioPath,coreBlockPath)
% 代码作用：
% 连接测试场景、核心模型和输出记录模块。

scenarioHandles = get_param( ...
    scenarioPath,'PortHandles');

coreHandles = get_param( ...
    coreBlockPath,'PortHandles');

for portIndex = 1:5
    add_line( ...
        modelName, ...
        scenarioHandles.Outport(portIndex), ...
        coreHandles.Inport(portIndex), ...
        'autorouting','on');
end

connectOutput( ...
    modelName,coreBlockPath,1, ...
    'jointVelocityCmd',1);

connectOutput( ...
    modelName,coreBlockPath,1, ...
    'Joint Velocity Scope',1);

connectOutput( ...
    modelName,coreBlockPath,1, ...
    'Log Joint Velocity',1);

connectOutput( ...
    modelName,coreBlockPath,2, ...
    'zoomStepRateCmd',1);

connectOutput( ...
    modelName,coreBlockPath,2, ...
    'Log Zoom Step Rate',1);

connectOutput( ...
    modelName,coreBlockPath,3, ...
    'controllerStatus',1);

connectOutput( ...
    modelName,coreBlockPath,3, ...
    'Controller Status Scope',1);

connectOutput( ...
    modelName,coreBlockPath,3, ...
    'Log Controller Status',1);
end


function validateConfiguration(cfgLocal)
% 代码作用：
% 检查Stage 1离线仿真需要的配置和机器人模型。

requiredFields = {
    'robot'
    'Ts'
    'qInitial'
    'zoomInitialSteps'
    'cameraIntrinsicsStage1'
    'cameraBodyName'
    'robotBaseName'
    'stage1CalibrationReady'
};

for i = 1:numel(requiredFields)
    if ~isfield(cfgLocal,requiredFields{i})
        error('StereoIBVSSim:CfgFieldMissing', ...
            'cfg缺少字段：%s',requiredFields{i});
    end
end

if numel(homeConfiguration(cfgLocal.robot)) ~= 7
    error('StereoIBVSSim:RobotDOF', ...
        'cfg.robot不是7自由度。');
end

if ~any(strcmp( ...
        cfgLocal.robot.BodyNames, ...
        cfgLocal.cameraBodyName))
    error('StereoIBVSSim:CameraBody', ...
        'cfg.robot中不存在%s。', ...
        cfgLocal.cameraBodyName);
end

Jtest = geometricJacobian( ...
    cfgLocal.robot, ...
    reshape(cfgLocal.qInitial,7,1), ...
    cfgLocal.cameraBodyName);

if ~isequal(size(Jtest),[6 7])
    error('StereoIBVSSim:JacobianSize', ...
        '测试Jacobian不是6×7。');
end

if ~logical(cfgLocal.stage1CalibrationReady)
    error('StereoIBVSSim:SimulationPermission', ...
        '离线仿真许可没有成功启用。');
end
end


function repairKinematicsBlocks(coreModelName,cfgLocal)
% 代码作用：
% 修正Get Jacobian和Get Transform使用的刚体名称。

jacobianBlock = [ ...
    coreModelName ...
    '/04_FR3_Camera_Kinematics/Get Jacobian'];

transformBlock = [ ...
    coreModelName ...
    '/04_FR3_Camera_Kinematics/Get Transform'];

setRequiredParameter( ...
    jacobianBlock,'RigidBodyTree','cfg.robot');

setRequiredParameter( ...
    jacobianBlock,'EndEffector', ...
    cfgLocal.cameraBodyName);

setOptionalParameter( ...
    jacobianBlock,'SimulateUsing', ...
    'Interpreted execution');

setRequiredParameter( ...
    transformBlock,'RigidBodyTree','cfg.robot');

setRequiredParameter( ...
    transformBlock,'SourceBody', ...
    cfgLocal.cameraBodyName);

setRequiredParameter( ...
    transformBlock,'TargetBody', ...
    cfgLocal.robotBaseName);

setOptionalParameter( ...
    transformBlock,'SimulateUsing', ...
    'Interpreted execution');

fprintf('Get Jacobian末端：%s\n', ...
    get_param(jacobianBlock,'EndEffector'));
end


function configureCallbacks( ...
    modelName,configFile,coreDir,configDir)
% 代码作用：
% 配置仿真模型初始化和清理回调。

escapedConfig = escapeQuotes(configFile);
escapedCoreDir = escapeQuotes(coreDir);
escapedConfigDir = escapeQuotes(configDir);

initCallback = sprintf([ ...
    'addpath(''%s'');' ...
    'addpath(''%s'');' ...
    'assignin(''base'',' ...
    '''STEREO_IBVS_SIMULATION_MODE'',true);' ...
    'run(''%s'');'], ...
    escapedCoreDir,escapedConfigDir,escapedConfig);

cleanupCallback = sprintf([ ...
    'assignin(''base'',' ...
    '''STEREO_IBVS_SIMULATION_MODE'',false);' ...
    'run(''%s'');'], ...
    escapedConfig);

set_param(modelName,'InitFcn',initCallback);
set_param(modelName,'StopFcn',cleanupCallback);
set_param(modelName,'CloseFcn',cleanupCallback);
end


function ensureSimulationOverride(configFile)
% 代码作用：
% 在主配置文件中加入默认关闭的离线仿真许可。

configText = fileread(configFile);
marker = '% STEREO_IBVS_SIM_OVERRIDE_BEGIN';

if contains(configText,marker)
    return;
end

backupFile = [configFile ...
    '.before_sim_override.bak'];

if ~isfile(backupFile)
    copyfile(configFile,backupFile);
end

overrideCode = sprintf([ ...
    '\n%%%% Stage 1离线仿真许可\n' ...
    '%% STEREO_IBVS_SIM_OVERRIDE_BEGIN\n' ...
    'cfg.simulationMode = false;\n' ...
    'if evalin(''base'',' ...
    '''exist(''''STEREO_IBVS_SIMULATION_MODE'''',' ...
    '''''var'''') == 1'')\n' ...
    '    cfg.simulationMode = logical(evalin(' ...
    '''base'',' ...
    '''STEREO_IBVS_SIMULATION_MODE''));\n' ...
    'end\n' ...
    'if cfg.simulationMode\n' ...
    '    cfg.stage1CalibrationReady = true;\n' ...
    'end\n' ...
    '%% STEREO_IBVS_SIM_OVERRIDE_END\n\n']);

insertMarker = '%% 写入MATLAB基础工作区';
insertLocation = strfind(configText,insertMarker);

if isempty(insertLocation)
    error('StereoIBVSSim:ConfigMarker', ...
        '配置文件中找不到“%% 写入MATLAB基础工作区”。');
end

insertIndex = insertLocation(1);

newText = [ ...
    configText(1:insertIndex-1) ...
    overrideCode ...
    configText(insertIndex:end)];

writeUtf8(configFile,newText);
end


function setRequiredParameter( ...
    blockPath,parameterName,parameterValue)
% 代码作用：
% 设置必须存在的模块参数。

if getSimulinkBlockHandle(blockPath) == -1
    error('StereoIBVSSim:MissingBlock', ...
        '找不到模块：%s',blockPath);
end

parameters = get_param(blockPath,'DialogParameters');

if ~isfield(parameters,parameterName)
    error('StereoIBVSSim:MissingParameter', ...
        '模块%s没有参数%s。', ...
        blockPath,parameterName);
end

set_param(blockPath,parameterName,parameterValue);
end


function setOptionalParameter( ...
    blockPath,parameterName,parameterValue)
% 代码作用：
% 设置可选模块参数。

parameters = get_param(blockPath,'DialogParameters');

if isfield(parameters,parameterName)
    set_param(blockPath,parameterName,parameterValue);
end
end


function addOutport( ...
    parentPath,blockName,portNumber, ...
    dimensions,position)
% 代码作用：
% 创建指定尺寸的Outport模块。

add_block( ...
    'simulink/Ports & Subsystems/Out1', ...
    [parentPath '/' blockName], ...
    'Position',position, ...
    'Port',num2str(portNumber), ...
    'PortDimensions',dimensions);
end


function addVectorConstant( ...
    parentPath,blockName,value,position)
% 代码作用：
% 创建保持列向量形状的Constant模块。

add_block( ...
    'simulink/Sources/Constant', ...
    [parentPath '/' blockName], ...
    'Position',position, ...
    'Value',value, ...
    'SampleTime','cfg.Ts', ...
    'VectorParams1D','off', ...
    'OutDataTypeStr','double');
end


function addScalarConstant( ...
    parentPath,blockName,value,position)
% 代码作用：
% 创建double标量Constant模块。

add_block( ...
    'simulink/Sources/Constant', ...
    [parentPath '/' blockName], ...
    'Position',position, ...
    'Value',value, ...
    'SampleTime','cfg.Ts', ...
    'OutDataTypeStr','double');
end


function addStep( ...
    parentPath,blockName,stepTime, ...
    beforeValue,afterValue,position)
% 代码作用：
% 创建离散Step模块。

add_block( ...
    'simulink/Sources/Step', ...
    [parentPath '/' blockName], ...
    'Position',position, ...
    'Time',stepTime, ...
    'Before',beforeValue, ...
    'After',afterValue, ...
    'SampleTime','cfg.Ts', ...
    'OutDataTypeStr','double');
end


function addSwitch(parentPath,blockName,position)
% 代码作用：
% 创建Switch模块。

add_block( ...
    'simulink/Signal Routing/Switch', ...
    [parentPath '/' blockName], ...
    'Position',position, ...
    'Criteria','u2 >= Threshold', ...
    'Threshold','0.5');
end


function addToWorkspace( ...
    modelName,blockName,variableName,position)
% 代码作用：
% 创建To Workspace模块。

add_block( ...
    'simulink/Sinks/To Workspace', ...
    [modelName '/' blockName], ...
    'Position',position, ...
    'VariableName',variableName, ...
    'SaveFormat','Timeseries', ...
    'MaxDataPoints','inf', ...
    'Decimation','1');
end


function connectOutput( ...
    modelName,sourceBlock,sourcePort, ...
    destinationBlock,destinationPort)
% 代码作用：
% 使用端口句柄建立输出分支。

sourceHandles = get_param( ...
    [modelName '/' sourceBlock], ...
    'PortHandles');

destinationHandles = get_param( ...
    [modelName '/' destinationBlock], ...
    'PortHandles');

add_line( ...
    modelName, ...
    sourceHandles.Outport(sourcePort), ...
    destinationHandles.Inport(destinationPort), ...
    'autorouting','on');
end


function writeUtf8(filePath,textContent)
% 代码作用：
% 使用UTF-8编码写入文本。

fileId = fopen(filePath,'w','n','UTF-8');

if fileId < 0
    error('StereoIBVSSim:WriteFile', ...
        '无法写入文件：%s',filePath);
end

cleanupObject = onCleanup(@() fclose(fileId));
fwrite(fileId,textContent,'char');
end


function escaped = escapeQuotes(textValue)
% 代码作用：
% 转义MATLAB回调字符串中的单引号。

escaped = strrep(textValue,'''','''''');
end


function result = samePath(pathA,pathB)
% 代码作用：
% 判断两个路径是否指向同一个文件。

canonicalA = char( ...
    java.io.File(pathA).getCanonicalPath());

canonicalB = char( ...
    java.io.File(pathB).getCanonicalPath());

result = strcmp(canonicalA,canonicalB);
end


function [projectDir,coreFile, ...
    configFile,simDir] = locateProjectFiles(projectDir)
% 代码作用：
% 自动查找核心模型和配置文件。
%
% 输出参数含义：
% projectDir：
% 找到的工程根目录。
%
% coreFile：
% 核心模型完整路径。
%
% configFile：
% 配置文件完整路径。
%
% simDir：
% 仿真模型输出目录。

scriptDir = fileparts(mfilename('fullpath'));

candidateRoots = {};

if ~isempty(projectDir)
    candidateRoots{end+1} = char(projectDir);
end

candidateRoots = [candidateRoots, {
    scriptDir
    fileparts(scriptDir)
    pwd
    fileparts(pwd)
}];

projectDir = '';
coreFile = '';
configFile = '';

for i = 1:numel(candidateRoots)
    root = candidateRoots{i};

    if isempty(root) || ~isfolder(root)
        continue;
    end

    structuredCore = fullfile( ...
        root,'core','stereo_ibvs_core.slx');

    structuredConfig = fullfile( ...
        root,'config','stereo_ibvs_config.m');

    flatCore = fullfile( ...
        root,'stereo_ibvs_core.slx');

    flatConfig = fullfile( ...
        root,'stereo_ibvs_config.m');

    if isfile(structuredCore) && ...
            isfile(structuredConfig)
        projectDir = root;
        coreFile = structuredCore;
        configFile = structuredConfig;
        break;
    end

    if isfile(flatCore) && isfile(flatConfig)
        projectDir = root;
        coreFile = flatCore;
        configFile = flatConfig;
        break;
    end
end

if isempty(projectDir)
    error('StereoIBVSSim:ProjectNotFound', ...
        ['没有找到stereo_ibvs_core.slx和' ...
         'stereo_ibvs_config.m。']);
end

simDir = fullfile(projectDir,'sim');

if ~isfolder(simDir)
    mkdir(simDir);
end
end
